#!/usr/bin/env bash                                                             
# Install nginx                                                                 

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo chmod -R 755 /var/www
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
