#!/usr/bin/env bash
# Creating nginx web server and redirecting a page to another page

apt-get update
apt-get install -y nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Holberton School" > /etc/nginx/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location = /redirect_me {
        return 301 https://euw.op.gg/summoner/userName=franklayn;
    }
}" > /etc/nginx/sites-available/default
service nginx reload
systemctl restart nginx
