#!/usr/bin/env bash
# shellcheck disable=SC2154
# configures a brand new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo sed -i "7i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
new_string="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/listen \[::\]:80 default_server;/a\ $new_string" /etc/nginx/sites-available/default
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
