#!/usr/bin/env bash
# Link sites-enabled to sites-available and restart nginx

sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
