#!/usr/bin/env bash
# This script displays the following informations in /etc/passwd:
#+ username
#+ user id
#+ Home directory path for the user

while read -r elm; do
echo "$elm" | cut -d: -f1,3,6
done < /etc/passwd
