#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd, using the while loop + IFS.
# Format: The user USERNAME is part of the GROUP_ID gang,
#+ lives in HOME_DIRECTORY and rides COMMAND/SHELL.
#+ USER ID's place is protected by the passcode PASSWORD,
#+ more info about the user here: USER ID INFO
while IFS=: read -r USERNAME PASSWORD USER_ID GID UID_INFO HOME_DIRECTORY COMMAND_SHELL; do
echo "The user $USERNAME is part of the $GID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $UID_INFO"
done < /etc/passwd
