#!/usr/bin/env bash
# Bash script that creates an RSA key pair:
# Private key name is holberton, number of bits in the created key is 4096
# and the created key protected by the passphrase betty

ssh-keygen -f holberton -b 4096 -N betty
